stocks:
  - ADANIENT
  - ADANIPORTS
  - ADANIPOWER
  - AMBUJACEM
  - APOLLOHOSP
  - ASHOKLEY
  - ASIANPAINT
  - AUBANK
  - BAJAJ-AUTO
  - BAJAJFINSV
  - BAJFINANCE
  - BALKRISIND
  - BANKBARODA
  - BATAINDIA
  - BEL
  - BERGEPAINT
  - BHARATFORG
  - BHARTIARTL
  - BIOCON
  - BOSCHLTD
  - BPCL
  - BRITANNIA
  - CANBK
  - CHOLAFIN
  - CIPLA
  - COALINDIA
  - COLPAL
  - CONCOR
  - DIVISLAB
  - DLF
  - DRREDDY
  - EICHERMOT
  - EXIDEIND
  - GAIL
  - GRASIM
  - HCLTECH
  - HDFCBANK
  - HDFCLIFE
  - HEROMOTOCO
  - HINDALCO
  - HINDUNILVR
  - HINDZINC
  - ICICIBANK
  - ICICIGI
  - ICICIPRULI
  - INDUSINDBK
  - INFY
  - IOC
  - ITC
  - JINDALSTEL
  - JSWSTEEL
  - KOTAKBANK
  - LTIM
  - LUPIN
  - MARUTI
  - NATIONALUM
  - NESTLEIND
  - NMDC
  - NTPC
  - ONGC
  - PIIND
  - PIDILITIND
  - POWERGRID
  - PVRINOX
  - RELIANCE
  - SBILIFE
  - SBIN
  - SHREECEM
  - SIEMENS
  - SRF
  - SUNPHARMA
  - TATACONSUM
  - TMCV
  - TATASTEEL
  - TCS
  - TECHM
  - TITAN
  - ULTRACEMCO
  - UPL
  - VEDL
  - WIPRO
  - ZEEL